version: "3.8"
services:
  gradle:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
      - "8080:8080"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ep-labjef
    volumes:
      - ./app:/app
    restart: always
    working_dir: /app

volumes:
  gradle_cache:
